### ISSUE TITLE
Allow to make several queries

### ISSUE THREAD

**Issue by matclab** [benr77/obsidian-gitlab-issues#15] opened 2022-11-25 12:49 UTC
For now we can only do one query to retrieve issues.
Thus it is not possible to get both opened issues I'm assigned and opened issues I've created.
It would be nice to allow for several queries.

Thank you very much for this very useful plugin !

**Comment by benr77** [comment] 2022-11-25 13:34
Thanks for your suggestion. This is basically a duplicate of #9 so I'll close this issue here. Please follow the other issue to stay updated.

**Closed by benr77** 2022-11-25 13:34 UTC
Labels: duplicate
